name: kaniko-action
description: Kaniko in GitHub Actions

inputs:
  executor:
    description: Image of Kaniko executor
    required: true
    default: gcr.io/kaniko-project/executor:v1.22.0
  cache:
    description: Enable caching layers
    required: true
    default: 'false'
  cache-repository:
    description: Remote repository for storing cached layers
    required: false
  cache-ttl:
    description: Cache timeout
    required: false
  push-retry:
    description: Number of retries for the push of an image
    required: false
  registry-mirror:
    description: Use registry mirror(s)
    required: false
  verbosity:
    description: Set the logging level
    required: false
  kaniko-args:
    description: Extra args to Kaniko executor
    required: false

  # compatible with https://github.com/docker/build-push-action
  build-args:
    description: List of build args
    required: false
  context:
    description: Path to the build context
    required: false
  file:
    description: Path to the Dockerfile
    required: false
  labels:
    description: List of metadata for an image
    required: false
  push:
    description: Push an image to the registry
    required: true
    default: 'false'
  tags:
    description: List of tags
    required: false
  target:
    description: Target stage to build
    required: false

outputs:
  digest:
    description: 'Image content-addressable identifier also called a digest'

runs:
  using: 'node20'
  main: 'dist/index.js'
