name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/example
      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: int128/kaniko-action
        id: build
        uses: ./
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures
      - run: test '${{ steps.build.outputs.digest }}'

      - name: int128/kaniko-action
        id: build-with-cache
        uses: ./
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
      - run: test '${{ steps.build-with-cache.outputs.digest }}'

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run check
      - uses: int128/update-generated-files-action@ffeee0fc8e9dc4718c1f36be68b9d89b2be28e51 # v2.109.0
