name: ts

on:
  pull_request:
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/ts.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm test
      - run: pnpm build

      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/example
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: int128/kaniko-action
        id: build
        uses: ./
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures
      - run: test '${{ steps.build.outputs.digest }}'

      - name: int128/kaniko-action
        id: build-with-cache
        uses: ./
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          context: tests/fixtures
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
      - run: test '${{ steps.build-with-cache.outputs.digest }}'

  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm run check
      - uses: int128/update-generated-files-action@03546ede83dedaefaed68cb5f79d08e14107af1c # v2.93.0
